name: 'Spin up runner'
description: 'Login to Bruno and create an ephemeral runner'
inputs:
  repository:
    description: 'Repository name'
    default: ${{ github.repository }}
  bruno_user:
    description: 'Bruno username'
    required: true
  url:
    description: 'URL to use'
    required: true 
outputs:
  command:
    description: 'SSH command to create runner'
runs:
  using: 'node20'
  main: 'dist/index.js'
